#include "main.h"

int main()
{
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
    
    GPIOD->MODER &= ~GPIO_MODER_MODER12;
    GPIOD->MODER |= GPIO_MODER_MODER12_0;
    GPIOD->OTYPER &= ~GPIO_OTYPER_OT12;
    GPIOD->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR12;
    GPIOD->PUPDR &= ~GPIO_PUPDR_PUPD12;
    GPIOD->BSRR |= GPIO_BSRR_BS12;

    GPIOD->MODER &= ~GPIO_MODER_MODER13;
    GPIOD->MODER |= GPIO_MODER_MODER13_0;
    GPIOD->OTYPER &= ~GPIO_OTYPER_OT13;
    GPIOD->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR13;
    GPIOD->PUPDR &= ~GPIO_PUPDR_PUPD13;
    GPIOD->BSRR |= GPIO_BSRR_BS13;

    GPIOD->MODER &= ~GPIO_MODER_MODER14;
    GPIOD->MODER |= GPIO_MODER_MODER14_0;
    GPIOD->OTYPER &= ~GPIO_OTYPER_OT14;
    GPIOD->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR14;
    GPIOD->PUPDR &= ~GPIO_PUPDR_PUPD14;
    GPIOD->BSRR |= GPIO_BSRR_BS14;
    
    GPIOD->MODER &= ~GPIO_MODER_MODER15;
    GPIOD->MODER |= GPIO_MODER_MODER15_0;
    GPIOD->OTYPER &= ~GPIO_OTYPER_OT15;
    GPIOD->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR15;
    GPIOD->PUPDR &= ~GPIO_PUPDR_PUPD15;
    GPIOD->BSRR |= GPIO_BSRR_BS15;

    while (1)
    {
        
    }
    
}

void GPIO_init_tamplate_v1_0()
{
    GPIOD->MODER &= ~GPIO_MODER_MODER12;
    GPIOD->MODER |= GPIO_MODER_MODER12_0;
    GPIOD->OTYPER &= ~GPIO_OTYPER_OT12;
    GPIOD->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR12;
    GPIOD->PUPDR &= ~GPIO_PUPDR_PUPD12;
    GPIOD->BSRR |= GPIO_BSRR_BS12;
}